### ISSUE TITLE
Would you be oki if we work together? + ANSI support?

### ISSUE THREAD

**Issue by Fox2Code** [ya0211/MRepo#21]
Hi, I think you made MRepo cause FoxMMM became terrible after I got health issues and was unable to maintain it.

I'm still having health issues but I wanted to know if you were interested in collaborating together, like adding ANSI color support with [AndroidANSI](https://github.com/Fox2Code/AndroidANSI), (my manager export `ANSI_SUPPORT=true` to tell it support ANSI)

I'll be happy to make the PR myself once my health is a bit better for ANSI coloring.

My telegram group: https://t.me/Fox2Code_Chat

You are allowed to advertise your projects here, since it's more of a community group and I consider you a member of the community, everyone can share their projects here.

Also if FoxMMM feel like it has been take over by Androidacy is because the only one willing to maintain FoxMMM was an Androidacy member that was new to Android, I would be really interested and **willing to pay you** to fix up FoxMMM if you are willing to do so.

![🦊](https://media.discordapp.net/stickers/859882634318446612.webp?size=160)

**Comment by Fox2Code** [comment]
To be honestly I'm thinking giving up FoxMMM to Androidacy and contribute to MRepo instead, I don't have the health to maintain FoxMMM because sometimes I cannot code for months in a row.

When I made FoxMMM it was simply because there was no other alternatives, but I can be happy by just being a contributor of MRepo.

Life has been really hard on me recently and I switched to do more minecraft for a bit because I found a relax community where I can just chill, but whatever I do I always become unreplacable somewhere, I have enough of it because of my health issues.

I'm already seeing doctors but the pain is too much for me to keep it all for myself anymore...

I'm sorry for being so emotional here, I will switch to using MRepo so I can  turn my brain off more often and don't think about fixing bugs.

**Comment by ya0211** [comment]
- MRepo is an open source project, it is OK to work together.
- About ANSI, I'm not sure whether to implement it, based on the description it seems to be for terminals
- About fixing up FoxMMM, I think I might not be able to get it done, I'm mostly using kotlin and jetpack compose (I'm amateur and new at Android 😶‍🌫️).
- Because of my interest, I learned Android and developed MRepo. It is very easy and enjoyable to do what we like.
- I wish you a speedy recovery, welcome to contribute to MRepo.

**Comment by Fox2Code** [comment]
Well, I'll try doing a PR for ANSI following your coding style when I feel better, a I have been sick for multiple years and have already given up on a speedy recovery.

ANSI is indeed a terminal thing but it allows module to print custom color in terminal, so it's more like a tool for module developers.

**Comment by Fox2Code** [comment]
Update: FoxMMM is now a Androidacy project.
https://github.com/Androidacy/AndroidacyModuleManager

Context is here:
https://github.com/Androidacy/AndroidacyModuleManager/issues/1

**Comment by IzzySoft** [comment]
@Fox2Code glad to see you here! The project can profit a lot from your background. As Sanmer wrote, I too wish you a speedy and complete recovery! Being a contributor to MRepo instead of having to shoulder a project lead hopefully can give you the peace to do things when you feel like, without having the full responsibility and feeling "hunted".

So while I'm no Android developer, as one of the minor contributors to this project here (including the back-end), I heartily welcome you – as Sanmer already did.
