### ISSUE TITLE
[Feature Request] Androidacy Magisk Modules Repository

### ISSUE THREAD

**Issue by orestis150** [ya0211/MRepo#28]
Hi, it would be nice to have an option to enable the Androidacy Repo since there are a lot of modules that are not available in the default repo and the alternative repo. Thanks in advance.

Here's the link of the repository: https://www.androidacy.com/magisk-modules-repository/

**Comment by orestis150** [comment]
I understand 😔 Maybe you could find a way to implement it by looking at Fox's MMM source, since the Androidacy Repo is integrated in that app🤔

**Comment by ya0211** [comment]
I will not use the implementation of fox mmm, I don't like nesting a web page in app.

**Comment by fr-jason-fr** [comment]
> I understand 😔 Maybe you could find a way to implement it by looking at Fox's MMM source, since the Androidacy Repo is integrated in that app🤔

You're barking up the wrong tree.

Fox has basically removed himself from development of the app and uses his time to chat and spread positivity in his TG group.

He handed over the development to another person/group, and they are the ones that are responsible for the horrible ad-ridden mess that it is.

I asked them already if they would consider allowing their repo to be accessed by MRepo (or any other module manager) and they said no.
They also support only Magisk and not KernelSU, nor do they plan to.

Your mindset is good but you ignore the fact that the vast majority that are on MRepo now had at some point left Androidacy Magisk Module Manager because of how poorly they manage it.

MRepo is the way forward now, it is essentially Androidacy's up and coming competition, whether or not it wants to be.

**Comment by Fox2Code** [comment]
To make stuff more clear:
- @androidacy-user do not wish to make an interface for MRepo. (Or any other app)
- I gave up the project to @androidacy-user cause they were the only one willing to maintain the repo.
- My health issues are still going on up to this day, and it's really frustrating cause I want to contribute a lot into open source app and projects.

Sure, FoxMMM became a mess after I was unable to maintain it, but I don't regret handing the project.

**Comment by orestis150** [comment]
> > I understand 😔 Maybe you could find a way to implement it by looking at Fox's MMM source, since the Androidacy Repo is integrated in that app🤔
> 
> You're barking up the wrong tree.
> 
> Fox has basically removed himself from development of the app because of health issues.
> 
> He handed over (gave up?) the development to another person/group, and they are the ones that are responsible for the horrible ad-ridden mess that it is.
> 
> I asked them already if they would consider allowing their repo to be accessed by MRepo (or any other module manager) and they said no. They also support only Magisk and not KernelSU, nor do they plan to.
> 
> Your mindset is good but you ignore the fact that the vast majority that are on MRepo now had at some point left Androidacy Magisk Module Manager because of how poorly they manage it.
> 
> MRepo is the way forward now, it is essentially Androidacy's up and coming competition, whether or not it wants to be.
> 
> If there is any light in the world maybe the MRepo Dev might work together with Fox on MRepo or something new together but that is hard to depend on because Fox's health issues are unknown, and all that is known about it is that it prevents the poor guy from developing as often as he would like.

Yep, MRepo seems more privacy friendly, that's why I prefer it. Better be that way.
